### ISSUE TITLE
Request to provide code, thank you

### ISSUE THREAD

**Issue by kidwhh** [astuti/ILA-DA#1]
I have read your paper  Instance Level Affinity Based Transfer for Unsupervised Domain Adaptation, and I am very interested in this paper.
I hope you can provide the code as soon as possible, which will be very helpful to me. Thank you very much

**Comment by CYDping** [comment]
I seconded  kidwhh. Thank you very much.

**Comment by kidwhh** [comment]
I hope to get the code of this paper as soon as possible, which will be very helpful to me @astuti

**Comment by GuangyuanHao** [comment]
So do I, Thanks.

**Comment by key-zhou** [comment]
I have read your paper Instance Level Affinity Based Transfer for Unsupervised Domain Adaptation, and I am very interested in this paper.
I hope you can provide the code as soon as possible, which will be very helpful to me. Thank you very much

**Comment by tarun005** [comment]
Hi all,
Sorry for this delay. The code is available now.
